"""Collect eval.json files and render ``models/REPORT.md``."""

from __future__ import annotations

import json
from pathlib import Path

from . import common
from .train import ORDER

TITLES = {
    "M0": "Viscosity", "M1": "Thermal surrogate", "M2": "Cycle forecaster", "M3": "Dyno classifier",
    "M4": "Failure/unseat risk", "M5": "VFD/impact estimator", "M6": "Anomaly detector",
    "O1": "SRP controller", "O2": "CSS planner", "O3": "RL competitor (PPO)",
}


def collect(root: Path | None = None) -> dict[str, dict]:
    root = Path(root) if root else common.models_dir()
    out = {}
    for m in ORDER:
        p = root / m / "eval.json"
        if p.exists():
            out[m] = json.loads(p.read_text())
    return out


def status(p: dict) -> str:
    v, t, b = p.get("value"), p.get("target"), p.get("baseline")
    if v is None:
        return "n/a"
    lower = p.get("direction", "higher") == "lower"
    met = t is None or (v <= t if lower else v >= t)
    beats = b is None or (v < b if lower else v > b)
    return ("target met" if met else "TARGET MISSED") + (", beats baseline" if beats else ", DOES NOT beat baseline")


def write_report(root: Path | None = None) -> Path:
    root = Path(root) if root else common.models_dir()
    evs = collect(root)
    L = ["# Mantle ML report", "", "Generated by `uv run mantle-ml report`. Every model was trained on "
         "physics-synthetic data unless the row says otherwise (M6 also uses real Petrobras 3W).", "",
         "| ID | Model | Metric | Value | Baseline | Target | Status | Train s | Size KB |",
         "|----|-------|--------|-------|----------|--------|--------|---------|---------|"]
    def f(x):
        return "-" if x is None else (f"{x:.4g}" if isinstance(x, (int, float)) else str(x))

    for m, ev in evs.items():
        p = ev.get("primary", {})
        kb = common.dir_size_bytes(root / m) / 1024
        L.append(f"| {m} | {TITLES.get(m, m)} | {p.get('name')} | {f(p.get('value'))} | "
                 f"{p.get('baseline_name', '')} {f(p.get('baseline'))} | {p.get('target_text') or f(p.get('target'))} | {status(p)} | "
                 f"{f(ev.get('train_seconds'))} | {kb:.0f} |")
    L += ["", "## Secondary metrics", ""]
    for m, ev in evs.items():
        L.append(f"### {m} {TITLES.get(m, '')}")
        for k, v in ev.get("metrics", {}).items():
            L.append(f"- {k}: {json.dumps(v)}")
        for k in ev.get("notes", []) if isinstance(ev.get("notes"), list) else []:
            L.append(f"- note: {k}")
        L.append("")
    p = root / "REPORT.md"
    p.write_text("\n".join(L) + "\n")
    return p
